from shapes import Triangle, Rectangle, Oval, Paper

sky = Rectangle()
sky.set_x(100)
sky.set_y(100)
sky.set_width(400)
sky.set_height(200)
sky.set_color("lightblue")
sky.draw()

sun = Oval()
sun.set_width(75)
sun.set_height(75)
sun.set_x(400)
sun.set_y(125)
sun.set_color("yellow")
sun.draw()

grass = Rectangle()
grass.set_x(100)
grass.set_y(300)
grass.set_width(400)
grass.set_height(200)
grass.set_color("green")
grass.draw()

wall = Rectangle()
wall.set_x(150)
wall.set_y(250)
wall.set_width(300)
wall.set_height(175)
wall.set_color("orange")
wall.draw()

door = Rectangle()
door.set_x(265)
door.set_y(300)
door.set_width(70)
door.set_height(125)
door.set_color("red")
door.draw()

path = Rectangle()
path.set_x(265)
path.set_y(425)
path.set_width(70)
path.set_height(75)
path.set_color("brown")
path.draw()

window_l = Rectangle()
window_l.set_x(175)
window_l.set_y(300)
window_l.set_width(65)
window_l.set_height(65)
window_l.set_color("lightblue")
window_l.draw()

window_r = Rectangle()
window_r.set_x(360)
window_r.set_y(300)
window_r.set_width(65)
window_r.set_height(65)
window_r.set_color("lightblue")
window_r.draw()

roof = Triangle(150, 250, 300, 150, 450, 250)
roof.set_color("purple")
roof.draw()

Paper.display()
